---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - gem update --system
  - gem install bundler
install:
  - bin/setup
script:
  - bundle exec rspec
  - gem build redis-claim
deploy:
  provider: rubygems
  api_key: "$RUBY_GEMS_API_KEY"
  on:
    tags: true